name: Hugo CICD

on:
  push:
    branches:
    - dev

# on:
#   # 1. Trigger the workflow every 2 hours
#   schedule:
#     - cron: "0 */2 * * *"    

jobs:
  build-deploy:
    name: Build & Deploy
    runs-on: ubuntu-18.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true  # fetch Hugo themes
        fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.70.0'
        extended: true

    - name: Build
      run: hugo --minify -e production && cp CNAME public/
      
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./public
        publish_branch: master  # deploying branch